name: Configure Azure environment

on:
  pull_request:
    types: [labeled]

env:
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"East US"'
  AZURE_WEBAPP_NAME: sydorchuksofia-ttt-app

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'spin up environment')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate Azure login
        run: echo "skip"

      - name: Create Azure resource group
        run: echo "skip"

      - name: Create Azure app service plan
        run: echo "skip"

      - name: Create webapp resource
        run: echo "skip"

      - name: Configure webapp to use GHCR
        run: echo "skip"

  destroy-azure-resources:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate destroy environment
        run: echo "skip"
